name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  pr-checks:
    name: Lint and build
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Cache Node.js modules / dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-pr-checks
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-docs-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-docs-${{ env.cache-name }}-
            ${{ runner.os }}-docs-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint js code
        run: npm run lint

      - name: Build docs
        run: npm run build
